matrix:
  include:
    - language: objective-c
      script:
        - xcodebuild test -project Framework/BaaS.xcodeproj -scheme BaaSTests -destination 'platform=iOS Simulator,name=iPhone XS Max' CODE_SIGNING_ALLOWED=NO

    - language: php
      php:
        - '5.6'
        - '7.1'
        - '7.2'
      script: 
        - phpunit Server/phptest.php